import type { ReactNode } from 'react';

/**
 * The deck components as the lesson page sees them in read mode: nothing. A lesson's slides
 * ride along in its module (see tools/remark-slides.mjs) and only the presentation view, which
 * swaps in the real components, draws them.
 *
 * Deck, Slide, SlideFigure and SlideNotes are also what an author writes for a hand-made deck;
 * LessonBody and DeckSource are internal, generated by the build, never written by hand.
 */
type Props = { children?: ReactNode; [key: string]: unknown };

export function Deck(_: Props) {
  return null;
}
export function Slide(_: Props) {
  return null;
}
export function SlideFigure(_: Props) {
  return null;
}
export function SlideNotes(_: Props) {
  return null;
}
export function DeckSource(_: Props) {
  return null;
}
/** The lesson's reading content, which the build wraps so presenting can leave it out. */
export function LessonBody({ children }: Props) {
  return <>{children}</>;
}
