/**
 * Self-host the site's fonts: copy the WOFF2 files out of the @fontsource-variable packages
 * into public/fonts/, and generate src/styles/fonts.css to match.
 *
 *   node tools/copy-fonts.mjs
 *
 * Run it after upgrading a font package; commit both outputs. Nothing at runtime depends on
 * the packages -- they are only where the files come from.
 *
 * Why self-hosted: the site used to load Inter and JetBrains Mono from Google Fonts, which
 * sent every visitor's IP address and page to Google before the first paint. Now nothing
 * leaves for a third party, and the fonts are cached with the site.
 *
 * The @font-face rules are taken from each package's own CSS rather than written by hand,
 * so the unicode-range subsets are exactly the publisher's. Only the Latin and Latin
 * Extended subsets are kept: they cover every character the site uses, including the minus
 * sign (U+2212) in prices, the dashes and the euro sign. Anything outside them falls back to
 * the system font, as it did under Google's subsets.
 *
 * File names carry the package version, so the server can cache /fonts/ as immutable: an
 * upgrade produces new names instead of changing files in place.
 */
import { copyFileSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(root, 'public', 'fonts');
const cssOut = join(root, 'src', 'styles', 'fonts.css');

// [package, css files to take faces from]
const FAMILIES = [
  // Body text. Italic too: lessons use emphasis, and without a real italic the browser
  // slants the upright letters instead, which is noticeably worse at reading sizes.
  ['inter', ['wght.css', 'wght-italic.css']],
  // Prices, tickers, R-multiples and code.
  ['jetbrains-mono', ['wght.css']],
  // Display face for headings and hero numbers.
  ['geist', ['wght.css']],
];
const SUBSETS = ['latin', 'latin-ext'];

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

const faces = [];
for (const [pkg, cssFiles] of FAMILIES) {
  const dir = join(root, 'node_modules', '@fontsource-variable', pkg);
  const version = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8')).version;
  for (const cssFile of cssFiles) {
    const css = readFileSync(join(dir, cssFile), 'utf8');
    // Each face is preceded by a comment naming its file, e.g. /* inter-latin-wght-normal */
    for (const m of css.matchAll(/\/\*\s*([a-z0-9-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)) {
      const [, name, block] = m;
      const subset = name.replace(`${pkg}-`, '').replace(/-wght-(normal|italic)$/, '');
      if (!SUBSETS.includes(subset)) continue;
      const file = `${name}-v${version}.woff2`;
      copyFileSync(join(dir, 'files', `${name}.woff2`), join(outDir, file));
      faces.push(`/* ${name} */\n` + block.replace(/url\([^)]*\)/, `url('/fonts/${file}')`));
    }
  }
}

const header = `/*
 * Generated by tools/copy-fonts.mjs -- do not edit by hand; re-run the script instead.
 * Self-hosted from the @fontsource-variable packages (SIL Open Font Licence 1.1).
 */
`;
writeFileSync(cssOut, header + faces.join('\n\n') + '\n');

const files = readdirSync(outDir);
console.log(`${faces.length} font faces, ${files.length} files in public/fonts/`);
for (const f of files.sort()) console.log(`  ${f}`);
